/* ---------------------------------------------------------------------------
** This software is in the public domain, furnished "as is", without technical
** support, and with no warranty, express or implied, as to its usefulness for
** any purpose.
**
** logrReader.c
** (Can Parse any log content generated by logr.h)
** Author: flouthoc (http:github.com/flouthoc)(flouthoc@gmail.com)
** -------------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include "stack.h"
#include "parser.h"

#define BUFFER_SIZE 1

int main(int argc, char *argv[]){

	char path[20];
	char buf[0];
	char flake;
	int fd;
	int n;
	stackNode *top;
	stackCreate(&top);

	if(!argv[1])
		strcpy(path,"data");
	else
		strcpy(path,argv[1]);

	fd = open(path, O_RDONLY, S_IRWXU);
	while((n = read(fd, buf, BUFFER_SIZE)) > 0){
		flake = buf[0];
		stackPush(&top,flake);					
	}
	//stackDisplay(&top);
	parse(&top);
	//	if(write(1, buf, n) != n )
	//		printf("Write Error");
	if(n < 0)
		printf("Read Error \n");








return 0;
}